FROM alpine:3.5

LABEL version="1.0"

# Specify multiple labels in a single instruction
LABEL maintainer.name = "QuanBlue" \
      maintainer.email="quannguyenthanh558@gmail.com"

RUN apk update
RUN apk add git